function [fitresult, gof, fun_out, fun_deriv_out] = createFit(phi, dntrap)
%CREATEFIT(PHI,DNTRAP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : phi
%      Y Output: dntrap
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Aug-2018 17:40:05


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( phi, dntrap );

% Set up fittype and options.
ft = fittype( 'poly8' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

fun_eval_str = sprintf(...
  'fun_out = @(x) %g*x.^8 + %g*x.^7 + %g*x.^6 + %g*x.^5 + %g*x.^4 + %g*x.^3 + %g*x.^2 + %g*x + %g;',...
  fitresult.p1,fitresult.p2,fitresult.p3,fitresult.p4,fitresult.p5,fitresult.p6,fitresult.p7,fitresult.p8,fitresult.p9);
eval(fun_eval_str)

fun_eval_str_deriv = sprintf(...
  'fun_deriv_out = @(x) 8*%g*x.^(8-1) + 7*%g*x.^(7-1) + 6*%g*x.^(6-1) + 5*%g*x.^(5-1) + 4*%g*x.^(4-1) + 3*%g*x.^(3-1) + 2*%g*x.^(2-1) + 1*%g*x.^(1-1) + 0*%g;',...
  fitresult.p1,fitresult.p2,fitresult.p3,fitresult.p4,fitresult.p5,fitresult.p6,fitresult.p7,fitresult.p8,fitresult.p9);
eval(fun_eval_str_deriv)

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'dntrap vs. phi', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel phi
% ylabel dntrap
% grid on
end
