function = yoon2008

bb=((kx*sin(alpha_angle))-(ky*cos(alpha_angle)) )*vde*cos(alpha_angle)/omega_ce;
lam=((  vthe*vthe*  ( -kz.^2 + ( (kx*sin(alpha_angle)) - ( ky*cos(alpha_angle))   ).^2) )/(2*omega_ce*omega_ce)) + ((kz*vde*cos(alpha_angle))/omega_ce) ;
chi=(z/vthe/( kx*cos(alpha_angle)  +  ky*sin(alpha_angle)    )  )  -  ( vde*sin(alpha_angle) / vthe );

return_residual = 1 - ...
    ((omega_pi*omega_pi/(kk*kk*vthi*vthi))*Zplasma_d(( z - ky*vdi)/(kk*vthi)  ))+...
    (2*omega_pe^2/(kk*kk*vthe*vthe) ) * (...
        1+...
        ((z - ky*vde)/(( kx*cos(alpha_angle) +  ky*sin(alpha_angle)     )*vthe)*...
        besselj(0,bb)*besseli(0,lam)*exp(-lam)*Zplasma(chi) ...
    )...
);