no02m = PIC('/Users/cecilianorgren/Data/PIC/no_hot_bg_n02_m100/data_h5/fields.h5');
%%
varstrs = {{'(Ex.*By-Ey.*Bx)./Babs.^2','vez','viz'},...
  {'vey','viy'},...
  {'Ey','vez.*Bx','-vex.*Bz'},...
  {'Ey + vez.*Bx - vex.*Bz','Ey + viz.*Bx - vix.*Bz'},...
  {'A'}}';

h = no02m.twpelim(20000).xlim(103 + [-0.5 0.5]).zlim([-2 2]).plot_line('z',varstrs);